In [23]:
import pandas as pd
import matplotlib as plt

In [36]:
df = pd.read_csv('annual-number-of-deaths-by-cause.csv')
DF = pd.read_csv('population.csv')

In [25]:
df.head(100)

,Entity,Code,Year,Execution,Meningitis (deaths),Lower respiratory infections (deaths),Intestinal infectious diseases (deaths),Protein-energy malnutrition (deaths),Terrorism (deaths),Cardiovascular diseases (deaths),...,Neonatal disorders (deaths),Alcohol use disorders (deaths),Natural disasters (deaths),Diarrheal diseases (deaths),Heat (hot and cold exposure) (deaths),Nutritional deficiencies (deaths),Suicide (deaths),Conflict (deaths),Diabetes (deaths),Poisonings (deaths)
0,Afghanistan,AFG,2007,15,9121.085992,29066.442137,461.195202,1846.996686,1199.0,53532.680495,...,28477.081107,96.027592,296.000026,10366.124292,160.930121,1941.282198,1378.571549,8216.000975,4691.007199,305.207239
1,Afghanistan,AFG,2008,17,8387.057275,26623.480551,437.718960,1681.270324,1092.0,53402.322328,...,28234.015837,98.308461,0.000000,8994.815981,156.860722,1765.980756,1411.783229,6748.999931,4750.240999,300.246001
2,Afghanistan,AFG,2009,0,7318.273004,24792.335792,415.776634,1568.095029,1065.0,53024.450772,...,27897.481121,100.088778,101.000000,7996.529795,152.144044,1647.863334,1428.808015,7562.996178,4784.225283,295.413907
3,Afghanistan,AFG,2010,NaN,7154.319444,23950.017286,332.253781,1541.841155,1157.0,52712.687821,...,27018.706951,102.648045,349.999997,7530.046788,151.683206,1619.355103,1457.157631,8117.000620,4825.933668,304.808594
4,Afghanistan,AFG,2011,2,6919.757958,23115.144836,299.758258,1468.203744,1525.0,52815.737495,...,27198.628720,105.565020,62.000000,7053.113394,150.311602,1543.182842,1496.192418,9061.000023,4954.293898,311.997686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,American Samoa,ASM,1991,NaN,1.177656,12.239996,0.952706,1.774760,NaN,68.164876,...,11.910660,0.308009,0.000000,1.311560,1.074433,1.859490,2.942479,0.000000,16.083324,0.385486
96,American Samoa,ASM,1992,NaN,1.189710,12.444813,0.947718,1.801325,NaN,70.369623,...,11.915099,0.317056,0.000000,1.300469,1.087108,1.889370,3.000647,0.000000,17.167882,0.390577
97,American Samoa,ASM,1993,NaN,1.203756,12.606450,0.960984,1.825095,NaN,71.873644,...,11.962377,0.323280,0.000000,1.286310,1.089076,1.916246,3.070508,0.000000,18.160812,0.393581
98,American Samoa,ASM,1994,NaN,1.214734,12.754844,0.953947,1.841325,NaN,73.508277,...,11.901719,0.333420,0.000000,1.278043,1.091878,1.935671,3.138566,0.000000,19.238132,0.396474
99,American Samoa,ASM,1995,NaN,1.221767,12.865659,0.927805,1.850042,NaN,74.824680,...,11.801362,0.343872,0.000000,1.281377,1.101134,1.947447,3.187174,0.000000,20.258092,0.398749

In [35]:
df.loc[df['Entity']=='Argentina']

,Entity,Code,Year,Execution,Meningitis (deaths),Lower respiratory infections (deaths),Intestinal infectious diseases (deaths),Protein-energy malnutrition (deaths),Terrorism (deaths),Cardiovascular diseases (deaths),...,Neonatal disorders (deaths),Alcohol use disorders (deaths),Natural disasters (deaths),Diarrheal diseases (deaths),Heat (hot and cold exposure) (deaths),Nutritional deficiencies (deaths),Suicide (deaths),Conflict (deaths),Diabetes (deaths),Poisonings (deaths)
224,Argentina,ARG,2007,NaN,556.903850,25400.629262,1.258517,1182.577307,NaN,100855.869590,...,4563.934351,903.360210,14.000000,596.603217,154.617366,1290.213689,4630.155412,0.0,8987.126193,405.415909
225,Argentina,ARG,2008,NaN,548.584506,25443.474559,1.256019,1101.646339,NaN,97556.233030,...,4501.571987,869.899980,11.000000,593.417806,113.973186,1198.473033,4670.235990,0.0,8514.335426,395.319722
226,Argentina,ARG,2009,NaN,542.897916,26617.890787,1.261716,1067.656284,0.0,98803.136025,...,4368.767711,837.586862,22.000000,603.462392,110.409337,1162.042050,4703.715160,0.0,8511.049201,392.653366
227,Argentina,ARG,2010,NaN,533.395878,27631.124386,1.261069,1038.198119,0.0,100413.024096,...,4300.762782,792.758835,7.000000,616.005516,108.446092,1134.488098,4662.014128,0.0,8496.227035,385.609374
228,Argentina,ARG,2011,NaN,522.717297,28531.284665,1.244435,1006.774281,0.0,101556.308652,...,4210.249602,781.337652,2.000000,626.389523,104.333895,1102.151235,4777.143330,0.0,8565.027826,386.145464
229,Argentina,ARG,2012,NaN,515.391123,29258.998764,1.233213,976.468160,0.0,101988.289764,...,4008.425438,773.712817,4.000000,630.352714,104.324725,1072.998967,4910.736901,0.0,8612.530387,385.805276
230,Argentina,ARG,2013,NaN,511.205370,30357.485214,1.221640,959.364043,0.0,102579.176957,...,4007.339071,762.449696,58.000001,644.724791,104.446625,1052.652516,4977.504327,0.0,8700.158549,386.622029
231,Argentina,ARG,2014,NaN,502.826835,30887.051942,1.208674,935.050352,0.0,101854.588271,...,3978.993942,757.237611,8.000000,655.853863,100.462041,1025.520738,4928.493898,0.0,8703.776735,370.941222
232,Argentina,ARG,2015,NaN,494.527440,31442.126995,1.195915,946.586378,0.0,103065.756658,...,3704.276003,765.650945,17.000000,666.825627,98.941440,1039.777692,4883.061340,0.0,8925.781783,356.663658
233,Argentina,ARG,2016,NaN,495.394123,31337.496003,1.184857,974.352851,0.0,105214.436492,...,3668.149345,819.503569,3.000000,655.986371,100.576883,1067.420020,4971.841163,0.0,9223.097523,359.629897
234,Argentina,ARG,1990,NaN,772.880513,8207.230969,1.414231,1032.299181,1.0,102810.352122,...,8739.161622,932.814571,21.000000,1095.738347,79.658499,1114.414371,3207.208396,1.0,5626.809890,396.128429
235,Argentina,ARG,1991,NaN,758.898809,8468.648078,1.404973,998.298627,1.0,101600.223892,...,8531.967702,983.329093,0.000000,1020.663302,84.687455,1080.436468,3354.079236,1.0,5800.866841,392.837002
236,Argentina,ARG,1992,NaN,743.301540,8872.556420,1.402869,962.797720,33.0,103431.622369,...,8041.108458,1060.888500,45.000000,940.823357,91.239432,1047.784184,3624.001526,32.0,6148.229023,388.860705
237,Argentina,ARG,1993,NaN,749.533062,9296.629035,1.398235,924.504826,NaN,101725.440249,...,7692.751903,1077.942694,15.000000,873.433422,94.760665,1008.276582,3740.150774,0.0,6365.775437,378.607335
238,Argentina,ARG,1994,NaN,719.904669,9710.894416,1.403251,902.100632,86.0,98786.453745,...,7262.287275,1121.901354,0.000000,812.915264,99.253795,983.998567,3907.937619,86.0,6540.101630,370.651359
239,Argentina,ARG,1995,NaN,726.584655,10724.751893,1.403344,948.437263,0.0,99053.523344,...,7060.767714,1148.454744,6.000000,808.808124,103.836537,1033.663187,4040.202850,0.0,6824.087962,368.068379
240,Argentina,ARG,1996,NaN,737.298450,11846.725898,1.389365,1017.581204,1.0,99428.152121,...,6926.771307,1180.648515,0.000000,801.194693,111.130632,1107.331532,4259.710969,1.0,7123.101306,373.462387
241,Argentina,ARG,1997,NaN,644.356476,13324.864548,1.373633,1143.755547,3.0,99454.023266,...,6560.614726,1198.957276,19.000000,803.481466,117.771987,1242.196831,4412.565476,3.0,7569.252684,372.214446
242,Argentina,ARG,1998,NaN,653.093877,14925.450822,1.357596,1267.796096,NaN,100710.753068,...,6531.415137,1140.328776,23.000000,791.426257,118.305931,1380.555904,4494.342367,0.0,8110.139312,363.639613
243,Argentina,ARG,1999,NaN,632.741019,16458.542813,1.346431,1339.387686,0.0,102428.750437,...,6086.367090,1099.715315,11.000000,756.584659,121.832333,1465.067906,4629.979230,0.0,8679.853341,369.158717
244,Argentina,ARG,2000,NaN,613.330126,17120.879325,1.334553,1346.779044,NaN,98064.681940,...,5869.783223,997.448827,19.000000,708.527828,152.271672,1469.092549,4597.184905,0.0,8625.929035,363.986272
245,Argentina,ARG,2001,NaN,600.776368,18532.871280,1.318904,1390.377582,0.0,98847.645063,...,5646.850381,952.458101,33.000000,689.789434,124.539179,1514.662308,4729.636485,0.0,8853.290187,360.412819
246,Argentina,ARG,2002,NaN,610.990859,19950.526970,1.298754,1488.856477,NaN,100822.096608,...,5868.220865,918.521979,21.000000,698.688030,122.476098,1622.952987,4793.557865,0.0,9072.943471,379.720989
247,Argentina,ARG,2003,NaN,609.906564,21537.318103,1.281133,1481.517515,0.0,102225.878928,...,5696.996666,903.931033,32.000000,674.269826,119.989370,1617.119698,4624.817243,0.0,9319.987785,381.983754
248,Argentina,ARG,2004,NaN,578.339234,22088.903887,1.259910,1358.365733,NaN,98797.998435,...,5201.014022,856.794667,7.000000,620.564035,115.470909,1482.046153,4379.049348,0.0,9088.588064,382.079050
249,Argentina,ARG,2005,NaN,556.206033,22723.054315,1.251626,1243.706197,0.0,96922.284295,...,4714.253891,863.040603,14.000000,587.847947,117.404670,1354.444574,4382.398642,0.0,8876.144781,392.078332
250,Argentina,ARG,2006,NaN,549.047942,23753.297435,1.253774,1183.945913,NaN,97307.486797,...,4512.160473,867.388073,3.000000,585.805200,115.330315,1291.712135,4434.023274,0.0,8768.676693,381.513852
251,Argentina,ARG,2017,NaN,494.948379,31058.142248,NaN,983.607619,0.0,105776.740522,...,3600.109017,857.090286,1.000000,651.446992,101.200180,1075.354199,5024.770844,0.0,9345.109432,357.743936

In [32]:
DATA = df.groupby(['Year']).mean()

In [33]:
DATA

,Meningitis (deaths),Lower respiratory infections (deaths),Intestinal infectious diseases (deaths),Protein-energy malnutrition (deaths),Terrorism (deaths),Cardiovascular diseases (deaths),Dementia (deaths),Kidney disease (deaths),Respiratory diseases (deaths),Liver diseases (deaths),...,Neonatal disorders (deaths),Alcohol use disorders (deaths),Natural disasters (deaths),Diarrheal diseases (deaths),Heat (hot and cold exposure) (deaths),Nutritional deficiencies (deaths),Suicide (deaths),Conflict (deaths),Diabetes (deaths),Poisonings (deaths)
Year,,,,,,,,,,,,,,,,,,,,,
1990,9315.515696,68796.991468,3886.642079,10343.740269,221.072165,249393.947809,21745.965432,12516.418506,67049.555467,18549.417238,...,58040.971017,2376.072381,900.350477,49639.914013,1207.336341,11423.021490,15577.234097,2108.384916,12578.625925,1616.984621
1991,9282.691062,68232.511287,3884.848451,10227.505913,191.568182,252961.761354,22546.504184,12748.987379,68311.783243,18981.834916,...,57581.855575,2517.967886,2621.701727,49305.255491,1243.245936,11292.974487,15975.645632,1785.669001,12977.345397,1628.277216
1992,9286.065424,67599.619178,3883.872305,10056.585540,189.779221,257417.300819,23287.027013,13074.676367,69513.062621,19396.115433,...,57092.235527,2774.808891,230.025416,48351.188615,1307.963092,11115.494669,16561.997928,1285.811466,13433.485431,1663.167677
1993,9235.644602,66898.636450,3870.870643,9880.162598,NaN,265107.130545,24139.956184,13372.733090,70531.809556,19813.388826,...,56455.794281,3162.873057,396.261014,47457.774788,1438.642756,10922.485096,17133.475519,1332.893913,13960.801694,1718.854422
1994,9141.499098,65977.497709,3869.323468,9756.013497,154.832215,269851.221728,24874.328898,13649.267431,71292.182596,20182.604404,...,55542.239263,3453.322565,233.158463,46596.702237,1531.537481,10786.026899,17538.528713,12218.733250,14435.758087,1740.749838
1995,9083.027834,65199.070325,3835.731431,11248.830428,132.673913,272103.836316,25628.434386,13942.951288,71711.993947,20532.137460,...,54841.653068,3482.016724,422.703370,45650.437622,1539.568522,12265.419479,17698.445344,1361.350045,14931.656134,1730.919273
1996,9277.187412,64154.640511,3786.810220,10920.487263,153.661765,272769.504812,26305.543324,14237.460385,72161.070040,20744.171813,...,53995.988877,3379.622546,283.147280,44458.088084,1449.212077,11902.720719,17448.502452,1811.833705,15437.851443,1696.607532
1997,8928.342659,63400.285609,3743.716949,10673.098465,248.272727,274192.175412,26992.842642,14633.178931,72987.625618,20972.855598,...,53546.760504,3280.284084,346.618560,43602.041642,1378.084553,11644.339717,17285.921357,2607.395160,15986.047835,1658.678627
1998,8753.649863,62489.791991,3692.892698,10419.357554,161.655172,276209.260781,27764.274311,15039.570719,73489.567315,21154.034548,...,53062.996084,3278.963358,884.172120,42906.666513,1397.755898,11375.925379,17183.226529,2339.233832,16502.798582,1631.841501
1999,8639.777469,61341.145664,3646.548607,10195.543812,99.794118,280846.738069,28608.690738,15439.062004,72822.442201,21383.080222,...,52372.107290,3431.560675,1375.126872,41997.607703,1373.252210,11127.647912,17223.995711,3294.375312,17016.327581,1642.225441
2000,8519.317963,60225.319990,3599.806142,10021.645833,119.000000,284916.724771,29407.910777,15845.811684,72414.718095,21640.126330,...,51666.794813,3580.364527,162.043865,41150.171132,1392.294173,10945.621258,17018.838803,2569.300518,17523.046707,1671.846192
2001,8354.381400,58940.506079,3548.961873,9702.094073,210.790909,288309.562306,30293.629410,16196.888296,71861.450329,21919.375598,...,50854.879532,3681.354048,533.484190,40166.514772,1414.171372,10592.888880,16458.647833,1259.962411,18032.110124,1677.218961
2002,8074.254569,57906.748807,3496.229564,9387.167393,161.966292,294100.855662,31305.566816,16645.386825,71666.767515,22230.945794,...,50054.940331,3804.619552,169.606211,39221.011365,1450.610027,10245.896704,16201.898124,1339.382379,18673.108651,1680.505903
2003,7908.520952,57064.890772,3443.436823,7398.484981,111.808989,299199.362891,32328.681656,17107.843753,71387.846772,22563.359258,...,49434.986661,3903.793104,631.123350,38338.381397,1577.655731,8232.477758,16242.693159,1156.723778,19286.208495,1679.953407
2004,7728.801828,56046.075172,3389.123197,7127.822378,257.149254,299297.716926,33104.059071,17385.968028,69950.197424,22803.011384,...,48596.039708,3943.862285,5060.102612,37634.290864,1396.134120,7938.412668,16286.418389,1145.664922,19622.561679,1687.022311
2005,7548.540114,55431.126622,3343.589913,6882.868648,237.412500,303226.602184,34241.060703,17897.625397,69057.729647,23182.649765,...,47761.114104,4048.394201,1538.148494,37136.802824,1436.701162,7682.279657,16436.219733,801.341838,20168.301365,1695.596590
2006,7446.314858,54736.381856,3292.350764,6672.713730,335.000000,301470.675693,35259.243715,18274.423170,68036.964180,23415.879159,...,46830.267447,3894.901799,351.403842,36887.342860,1339.184169,7461.103984,16128.444512,1068.181701,20435.699817,1646.479525
2007,7279.556677,54229.943844,3243.112244,6467.038008,422.769231,303882.167373,36510.686584,18767.090985,68014.968313,23645.754974,...,45864.405170,3805.068179,295.628072,36444.012242,1264.830098,7248.298793,15977.849249,1091.607842,20791.119429,1619.474482
2008,7029.323682,53925.856718,3192.990549,6283.015815,261.628571,310223.691959,38000.872411,19437.844869,68703.023528,23981.713708,...,44975.133250,3797.988217,5071.612990,36149.850124,1242.393701,7067.144976,16047.704081,1128.443879,21353.426133,1627.054313
2009,6880.417157,53608.393184,3144.147660,6145.748907,289.781250,315362.800627,39525.845295,20133.898280,69634.182221,24226.387952,...,44101.217103,3686.559514,189.694041,36103.705236,1209.419113,6930.162092,16054.334374,1321.999444,21847.051472,1613.065286
2010,6688.687608,53315.451262,3080.300674,6216.893379,269.896552,322189.348472,41213.277690,20805.434403,70607.363091,24487.293407,...,43189.945543,3664.622948,5287.287497,35925.568968,2426.987014,7008.810543,16127.099614,968.117782,22358.197294,1612.799633
2011,6564.839530,53193.135483,3056.935456,5995.901007,277.955056,326808.863159,42926.683751,21480.266245,71114.440569,24697.760934,...,42249.698759,3584.798941,681.727067,34643.025141,1169.625488,6769.847893,16054.342157,1797.945679,23009.991035,1589.492132
2012,6406.344237,53004.574877,3024.446184,5592.586976,479.288660,331828.531969,44491.720578,22095.011958,71144.699957,24935.835074,...,41271.755943,3564.329815,133.835272,33303.760682,1173.403704,6351.475352,15897.353410,1996.884151,23767.516824,1573.920224
2013,6312.601778,52744.579404,2987.383479,5387.484322,618.694444,335055.824558,45966.643668,22702.118402,71334.613318,25156.077760,...,40139.855567,3583.231677,377.638586,32121.812818,1133.354667,6129.916221,15756.961928,2093.651814,24449.233373,1563.585157
2014,6215.461083,52591.312425,2950.031808,5215.160092,1181.150442,341998.224851,47738.798538,23399.781819,72595.603786,25528.564353,...,38997.597063,3638.468231,131.333134,31252.764285,1119.169937,5952.833885,15810.282741,3325.080575,25380.425736,1555.128367
2015,6070.643560,52711.489953,2894.878200,5088.336281,1040.705357,352559.776503,49838.287146,24183.791157,74586.156543,26025.074376,...,37789.540922,3736.048858,269.670765,30458.201503,1163.109849,5824.763238,15857.792472,2446.442671,26403.776930,1554.843760
2016,6022.485397,52635.206374,2827.379961,4946.240099,864.570248,360266.097392,51644.396066,24817.780259,76268.942532,26542.221577,...,36416.983084,3801.286010,148.727130,29938.726207,1100.306456,5677.691024,15962.336539,2815.024710,27348.138027,1539.692172
2017,5867.637180,52373.629121,NaN,4856.276278,689.869565,365604.748092,53197.221094,25077.611969,78005.540780,27028.720519,...,35105.258192,3867.345967,192.250024,30274.690952,1083.936575,5583.253071,16061.981373,2352.336570,27810.533885,1513.030507

In [68]:
arg = DF.loc[DF['Entity']=='Argentina']

In [69]:
arg

         Entity Code  Year  Population
1582  Argentina  ARG  1800      534000
1583  Argentina  ARG  1801      534000
1584  Argentina  ARG  1802      534000
1585  Argentina  ARG  1803      534000
1586  Argentina  ARG  1804      534000
...         ...  ...   ...         ...
1797  Argentina  ARG  2015    43075000
1798  Argentina  ARG  2016    43508000
1799  Argentina  ARG  2017    43937000
1800  Argentina  ARG  2018    44361000
1801  Argentina  ARG  2019    44781000

[220 rows x 4 columns]

In [70]:
year_list = list(range(1950,2017))

In [71]:
print(year_list)

[1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]

In [ ]:
for year in year_list:
    if year in year_list:
        pop = arg.iloc()